Web90TvCore2/Pages/ImageBrowser.cshtml.cs
using Imageflow.Fluent;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.FileProviders;
using System;
using System.Threading.Tasks;
using System.IO;
using System.Linq;
using System.Collections.Generic;

//باید نام پروژه خودمان را قرار دهیم
namespace Web90TvCore2.Pages
{
    public class ImageBrowserModel : PageModel
    {
        public ImageBrowserModel(IConfiguration config, IHostingEnvironment env)
        {
            _config = config;
            _env = env;
        }

        //properties
        private IConfiguration _config;
        private IHostingEnvironment _env;

        [BindProperty]
        public string ResizeMessage { get; set; }

        [BindProperty]
        public string NewDirectoryName { get; set; }

        [BindProperty]
        public string SearchTerms { get; set; }

        [BindProperty]
        public string ResizeWidth { get; set; }

        [BindProperty]
        public string ResizeHeight { get; set; }

        public string ImageAspectRatio { get; set; }

        [BindProperty]
        public IFormFile UploadedImageFile { get; set; }

        [BindProperty]
        public string ImageListValue { get; set; } = "";

        [BindProperty]
        public string ImageUrl { get; set; }

        [BindProperty]
        public string NewImageName { get; set; }

        public bool IsDeleteDirectoryBtnEnabled => ImageFolder != "";
        public bool IsImageBtnsEnabled => ImageList.Any();

        /// <summary>
        /// The URL to the currently selected image folder.
        /// </summary>
        [BindProperty]
        public string ImageFolder { get; set; } = "";

        /// <summary>
        /// The URL to the root image folder.
        /// </summary>
        private string ImageFolderRoot => _config["FilesRoot"] != null ? $"/{_config["ImageRoot"].Trim('/')}/" : "";

        /// <summary>
        /// The file path to the root image folder.
        /// </summary>
        private string FileImageFolderRoot => Path.Combine(_env.WebRootPath, ImageFolderRoot.Trim('/', '\\')) + "\\";

        /// <summary>
        /// The file path to the currently selected image folder.
        /// </summary>
        private string FileImageFolder => Path.Combine(FileImageFolderRoot, ImageFolder ?? "") + "\\";

        // Methods

        public Task OnGetAsync()
        {
            ResizeMessage = "";
            return OnPostChangeDirectoryAsync();
        }

        public IEnumerable<SelectListItem> DirectoryList =>
            new[] { new SelectListItem { Text = "Root", Value = "" } }.Concat(
                Directory.GetDirectories(FileImageFolderRoot)
                    .Select(d => Path.GetFileName(d))
                    .Select(d => new SelectListItem { Text = d, Value = d })
            );

        public IEnumerable<SelectListItem> ImageList {
            get
            {
                var files = Directory.GetFiles(FileImageFolder, "*" + SearchTerms?.Replace(" ", "*") + "*")
                    .Where(i => IsImage(i))
                    .Select(i => Path.GetFileName(i))
                    .Select(i => new SelectListItem { Text = i, Value = i });
                if (ImageListValue == "" && files.Any())
                    ImageListValue = files.First().Text;
                return files;
            }
        }

        public Task OnPostChangeDirectoryAsync()
        {
            SearchTerms = "";
            ImageListValue = "";
            return OnPostSelectImageAsync();
        }

        public Task OnPostDeleteFolder()
        {
            Directory.Delete(FileImageFolder, true);
            ImageFolder = "";
            return OnPostChangeDirectoryAsync();
        }

        public Task OnPostCreateFolderAsync()
        {
            string name = UniqueDirectory(NewDirectoryName);
            Directory.CreateDirectory(FileImageFolderRoot + name);
            ImageFolder = name;
            return OnPostChangeDirectoryAsync();
        }

        public async Task OnPostSelectImageAsync()
        {
            if (!IsImageBtnsEnabled)
            {
                ImageUrl = "";
                ResizeWidth = "";
                ResizeHeight = "";
                return;
            }

            ImageUrl = ImageFolderRoot + (string.IsNullOrEmpty(ImageFolder) ? "" : ImageFolder + "/") + ImageListValue + "?" + new Random().Next(1000);
            var img = await GetImageSize(FileImageFolder + ImageListValue);
            ResizeWidth = img.Width.ToString();
            ResizeHeight = img.Height.ToString();
            ImageAspectRatio = "" + img.Width / (float)img.Height;
        }

        public Task OnPostRenameImageAsync()
        {
            string filename = UniqueFilename(NewImageName);
            System.IO.File.Move(FileImageFolder + ImageListValue, FileImageFolder + filename);
            ImageListValue = filename;
            return OnPostSelectImageAsync();
        }

        public Task OnPostDeleteImageAsync()
        {
            System.IO.File.Delete(FileImageFolder + ImageListValue);
            ImageListValue = "";
            return OnPostSelectImageAsync();
        }

        public async Task OnPostResizeImageAsync()
        {
            uint width = Convert.ToUInt32(ResizeWidth);
            uint height = Convert.ToUInt32(ResizeHeight);

            byte[] image = System.IO.File.ReadAllBytes(FileImageFolder + ImageListValue);
            image = await ResizeImageBytes(image, width, height);
            System.IO.File.WriteAllBytes(FileImageFolder + ImageListValue, image);

            ResizeMessage = "Image successfully resized!";
            await OnPostSelectImageAsync();
        }

        public async Task OnPostUploadAsync()
        {
            if (IsImage(UploadedImageFile.FileName))
            {
                string filename = UniqueFilename(UploadedImageFile.FileName);
                var stream = new MemoryStream();
                UploadedImageFile.CopyTo(stream);
                byte[] image = await ResizeImageBytes(stream.ToArray(), 1024, 1024); //make 1024x1024 the largest image size
                System.IO.File.WriteAllBytes(FileImageFolder + filename, image);

                ImageListValue = filename;
                await OnPostSelectImageAsync();
            }
        }

        //util methods
        private bool IsImage(string file)
        {
            return file.EndsWith(".jpg", StringComparison.CurrentCultureIgnoreCase) ||
                file.EndsWith(".gif", StringComparison.CurrentCultureIgnoreCase) ||
                file.EndsWith(".png", StringComparison.CurrentCultureIgnoreCase);
        }

        protected string UniqueFilename(string filename)
        {
            string newfilename = filename;

            for (int i = 1; System.IO.File.Exists(FileImageFolder + newfilename); i++)
            {
                newfilename = filename.Insert(filename.LastIndexOf('.'), "(" + i + ")");
            }

            return newfilename;
        }

        protected string UniqueDirectory(string directoryname)
        {
            string newdirectoryname = directoryname;

            for (int i = 1; Directory.Exists(FileImageFolderRoot + newdirectoryname); i++)
            {
                newdirectoryname = directoryname + "(" + i + ")";
            }

            return newdirectoryname;
        }

        protected async Task<byte[]> ResizeImageBytes(byte[] imageData, uint? desiredWidth, uint? desiredHeight)
        {
            using (var job = new FluentBuildJob())
            {
                var res = await job.Decode(imageData).ConstrainWithin(desiredWidth, desiredHeight)
                    .EncodeToBytes(new LibJpegTurboEncoder()).FinishAsync();
                var bytes = res.First.TryGetBytes();
                return bytes.HasValue ? bytes.Value.Array : new byte[] {};
            }
        }

        protected async Task<(int Width, int Height)> GetImageSize(string filename)
        {
            using (var job = new FluentBuildJob())
            {
                var imageData = System.IO.File.ReadAllBytes(filename);
                var res = await job.Decode(imageData)
                    .EncodeToBytes(new LibJpegTurboEncoder()).FinishAsync();
                return (res.First.Width, res.First.Height);
            }
        }
    }
}

Web90TvCore2/Pages/LinkBrowser.cshtml.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.FileProviders;
using System;
using System.Threading.Tasks;
using System.IO;
using System.Linq;
using System.Collections.Generic;

//نام پروژه خود را قرار میدهیم
namespace Web90TvCore2.Pages
{
    public class LinkBrowserModel : PageModel
    {
        public LinkBrowserModel(IConfiguration config, IHostingEnvironment env)
        {
            _config = config;
            _env = env;
        }

        //properties
        private IConfiguration _config;
        private IHostingEnvironment _env;

        [BindProperty]
        public string ResizeMessage { get; set; }

        [BindProperty]
        public string NewDirectoryName { get; set; }

        [BindProperty]
        public string SearchTerms { get; set; }

        [BindProperty]
        public string ResizeWidth { get; set; }

        [BindProperty]
        public string ResizeHeight { get; set; }

        public string FileAspectRatio { get; set; }

        [BindProperty]
        public IFormFile UploadedFile { get; set; }

        [BindProperty]
        public string FileListValue { get; set; } = "";

        [BindProperty]
        public string FileUrl { get; set; }

        [BindProperty]
        public string NewFileName { get; set; }

        public bool IsDeleteDirectoryBtnEnabled => FileFolder != "";
        public bool IsFileBtnsEnabled => FileList.Any();

        /// <summary>
        /// The URL to the currently selected file folder.
        /// </summary>
        [BindProperty]
        public string FileFolder { get; set; } = "";

        /// <summary>
        /// The URL to the root file folder.
        /// </summary>
        private string FileFolderRoot => _config["FilesRoot"] != null ? $"/{_config["FilesRoot"].Trim('/')}/" : "";

        /// <summary>
        /// The file path to the root file folder.
        /// </summary>
        private string FilePathFolderRoot => Path.Combine(_env.WebRootPath, FileFolderRoot.Trim('/', '\\')) + "\\";

        /// <summary>
        /// The file path to the currently selected file folder.
        /// </summary>
        private string FilePathFolder => Path.Combine(FilePathFolderRoot, FileFolder ?? "") + "\\";

        // Methods

        public Task OnGetAsync()
        {
            ResizeMessage = "";
            return OnPostChangeDirectoryAsync();
        }

        public IEnumerable<SelectListItem> DirectoryList =>
            new[] { new SelectListItem { Text = "Root", Value = "" } }.Concat(
                Directory.GetDirectories(FilePathFolderRoot)
                    .Select(d => Path.GetFileName(d))
                    .Select(d => new SelectListItem { Text = d, Value = d })
            );

        public IEnumerable<SelectListItem> FileList {
            get
            {
                var files = Directory.GetFiles(FilePathFolder, "*" + SearchTerms?.Replace(" ", "*") + "*")
                    .Where(i => IsFile(i))
                    .Select(i => Path.GetFileName(i))
                    .Select(i => new SelectListItem { Text = i, Value = i });
                if (FileListValue == "" && files.Any())
                    FileListValue = files.First().Text;
                return files;
            }
        }

        public Task OnPostChangeDirectoryAsync()
        {
            SearchTerms = "";
            FileListValue = "";
            return OnPostSelectFileAsync();
        }

        public Task OnPostDeleteFolder()
        {
            Directory.Delete(FilePathFolder, true);
            FileFolder = "";
            return OnPostChangeDirectoryAsync();
        }

        public Task OnPostCreateFolderAsync()
        {
            string name = UniqueDirectory(NewDirectoryName);
            Directory.CreateDirectory(FilePathFolderRoot + name);
            FileFolder = name;
            return OnPostChangeDirectoryAsync();
        }

        public Task OnPostSelectFileAsync()
        {
            if (!IsFileBtnsEnabled)
            {
                FileUrl = "";
                ResizeWidth = "";
                ResizeHeight = "";
                return Task.CompletedTask;
            }

            FileUrl = FileFolderRoot + (string.IsNullOrEmpty(FileFolder) ? "" : FileFolder + "/") + FileListValue + "?" + new Random().Next(1000);
            return Task.CompletedTask;
        }

        public Task OnPostRenameFileAsync()
        {
            string filename = UniqueFilename(NewFileName);
            System.IO.File.Move(FilePathFolder + FileListValue, FilePathFolder + filename);
            FileListValue = filename;
            return OnPostSelectFileAsync();
        }

        public Task OnPostDeleteFileAsync()
        {
            System.IO.File.Delete(FilePathFolder + FileListValue);
            FileListValue = "";
            return OnPostSelectFileAsync();
        }

        public async Task OnPostUploadAsync()
        {
            if (IsFile(UploadedFile.FileName))
            {
                string filename = UniqueFilename(UploadedFile.FileName);
                var stream = new MemoryStream();
                UploadedFile.CopyTo(stream);
                System.IO.File.WriteAllBytes(FilePathFolder + filename, stream.ToArray());

                FileListValue = filename;
                await OnPostSelectFileAsync();
            }
        }

        //util methods
        private bool IsFile(string file)
        {
            return file.EndsWith(".jpg", StringComparison.CurrentCultureIgnoreCase) ||
                file.EndsWith(".gif", StringComparison.CurrentCultureIgnoreCase) ||
                file.EndsWith(".png", StringComparison.CurrentCultureIgnoreCase);
        }

        protected string UniqueFilename(string filename)
        {
            string newfilename = filename;

            for (int i = 1; System.IO.File.Exists(FilePathFolder + newfilename); i++)
            {
                newfilename = filename.Insert(filename.LastIndexOf('.'), "(" + i + ")");
            }

            return newfilename;
        }

        protected string UniqueDirectory(string directoryname)
        {
            string newdirectoryname = directoryname;

            for (int i = 1; Directory.Exists(FilePathFolderRoot + newdirectoryname); i++)
            {
                newdirectoryname = directoryname + "(" + i + ")";
            }

            return newdirectoryname;
        }
    }
}

Web90TvCore2/Pages/ImageBrowser.cshtml
@* razor page *@
@page

@*//باید نام پروژه خودمان را قرار دهیم*@
@model Web90TvCore2.Pages.ImageBrowserModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<html>
<head>
    <title>انتخاب عکس</title>
    <style type="text/css">

        body {
            margin: 0px;
        }

        form {
            width: 750px;
            background-color: #E3E3C7;
        }

        h1 {
            padding: 15px;
            margin: 0px;
            padding-bottom: 0px;
            font-family: Arial;
            font-size: 14pt;
            color: #737357;
        }
    </style>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        <div>
            <h1>انتخاب عکس</h1>

            <table border="1" style="background-color:#F1F1E3; margin:15px; width: 720px; border-spacing: 0px;">
                <tr>
                    <td style="width: 396px; vertical-align: middle; text-align: center; padding: 10px;">
                        <img src="@(Model.ImageUrl)" style="max-height: 450px; max-width: 380px;">
                        <input type="hidden" asp-for="ImageUrl" />
                    </td>
                    <td style="width: 324px; vertical-align: top; padding: 10px;">


                        <input id="changeDirectory" type="submit" asp-page-handler="ChangeDirectory" style="display:none;" />

                        <input type="hidden" asp-for="NewDirectoryName" />

                        <br /><br />
                        <div>
                            <br />
                            <input type="text" asp-for="SearchTerms" />
                            <input type="submit" asp-page-handler="Search" value="جستجو" />
                            <br />
                        </div>
                        <select id="imageList" asp-for="ImageListValue" asp-items="Model.ImageList" size="12" onchange="document.getElementById('selectImage').click()" style="width: 280px; height: 180px;"></select>
                        <input id="selectImage" type="submit" asp-page-handler="SelectImage" style="display: none;" />
                        <input id="newImageName" type="hidden" asp-for="NewImageName" />

                        <input type="submit" asp-page-handler="DeleteImage" value="حذف عکس" disabled="@(!Model.IsImageBtnsEnabled ? "disabled" : null)" onclick="return confirm('Are you sure you want to delete this image?');" />
                        <br />
                        <br />
                        Resize:<br />
                        <input id="ResizeWidth" type="text" asp-for="ResizeWidth" disabled="@(!Model.IsImageBtnsEnabled ? "disabled" : null)" onchange="maintainRatio(true, this.value)" style="width: 50px;" />
                        x
                        <input id="ResizeHeight" type="text" asp-for="ResizeHeight" disabled="@(!Model.IsImageBtnsEnabled ? "disabled" : null)" onchange="maintainRatio(false, this.value)" style="width: 50px;" />
                        <input type="submit" value="تغییر اندازه عکس" asp-page-handler="ResizeImage" disabled="@(!Model.IsImageBtnsEnabled ? "disabled" : null)" /><br />
                        <div style="color: red;">@(Model.ResizeMessage)</div>
                        <br /><br />
                        Upload Image: (10 MB max)
                        <input type="file" asp-for="UploadedImageFile" />
                        <input type="submit" asp-page-handler="Upload" style="background-color:lightblue; border-radius:4px;" value="آپلود" /><br />
                        <br />
                    </td>
                </tr>
            </table>

            <div style="text-align: center;">
                <input type="submit" value="استفاده از عکس" class="btn btn-success" asp-page-handler="Clear" onclick="ok()" />
                <input type="submit" value="برگشت" class="btn btn-danger" asp-page-handler="Clear" onclick="closeDialog()" />
                <br /><br />
            </div>
        </div>
    </form>
    <script>
		document.getElementById("imageList").focus();

		function newDirectory() {
			var name = prompt('Enter name of folder:');
			if (name == null || name == '') {
				return false;
			}
			document.getElementById('NewDirectoryName').value = name;
			return true;
		}

		function maintainRatio(isWidth, value) {
			var ratio = @(Model.ImageAspectRatio);
			var field = document.getElementById(isWidth ? 'ResizeHeight' : 'ResizeWidth');
			field.value = isWidth ? parseInt(value / ratio) : parseInt(value * ratio);
		}

		function renameImage() {
			var name = prompt('Enter new filename:','@(Model.ImageListValue)');
			if (name == null || name == '')
				return false;
			document.getElementById('newImageName').value = name;
			return true;
		}

		function ok() {
			var dialog = window.top.opener.CKEDITOR.dialog.getCurrent();
			dialog.setValueOf('info', 'txtUrl', encodeURI('@(Model.ImageUrl)'));
			closeDialog();
		}

		function closeDialog() {
			window.top.close();
			window.top.opener.focus();
		}
    </script>
</body>
</html>

Web90TvCore2/Pages/LinkBrowser.cshtml
@* razor page *@
@page

@*//باید نام پروژه خودمان را قرار دهیم*@
@model Web90TvCore2.Pages.LinkBrowserModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<html>
<head>
    <title>Link Browser</title>
    <style type="text/css">

        body {
            margin: 0px;
        }

        form {
            width: 500px;
            background-color: #E3E3C7;
        }

        h1 {
            padding: 15px;
            margin: 0px;
            padding-bottom: 0px;
            font-family: Arial;
            font-size: 14pt;
            color: #737357;
        }

        .tab-panel .ajax__tab_body {
            background-color: #E3E3C7;
        }
    </style>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        <div>
            <h1>Link Browser</h1>
            <table border="1" style="background-color: #F1F1E3; width: 100%; border-spacing: 0px;">
                <tr>
                    <td style="vertical-align: top; padding: 10px;">
                        Folders:<br />
                        <select asp-for="FileFolder" asp-items="Model.DirectoryList" onchange="document.getElementById('changeDirectory').click()" style="width:160px;"></select>
                        <input id="changeDirectory" type="submit" asp-page-handler="ChangeDirectory" style="display:none;" />
                        <input type="submit" asp-page-handler="DeleteFolder" value="Delete" disabled="@(!Model.IsDeleteDirectoryBtnEnabled ? "disabled" : null)" onclick="return confirm('Are you sure you want to delete this folder and all its contents?');">
                        <input type="hidden" asp-for="NewDirectoryName" />
                        <input type="submit" asp-page-handler="CreateFolder" value="New" onclick="return newDirectory()" />
                        <br /><br />
                        <div>
                            Search:<br />
                            <input type="text" asp-for="SearchTerms" />
                            <input type="submit" asp-page-handler="Search" value="Go" />
                            <br />
                        </div>
                        <select id="fileList" asp-for="FileListValue" asp-items="Model.FileList" size="12" onchange="document.getElementById('selectFile').click()" style="width: 280px; height: 180px;"></select>
                        <input id="selectFile" type="submit" asp-page-handler="SelectFile" style="display: none;" />
                        <input id="newFileName" type="hidden" asp-for="NewFileName" />
                        <input type="submit" asp-page-handler="RenameFile" value="Rename" disabled="@(!Model.IsFileBtnsEnabled ? "disabled" : null)" onclick="return renameFile()" />
                        <input type="submit" asp-page-handler="DeleteFile" value="Delete" disabled="@(!Model.IsFileBtnsEnabled ? "disabled" : null)" onclick="return confirm('Are you sure you want to delete this file?');" />
                        <br />
                        <br />
                        Upload File: (10 MB max)<br />
                        <input type="file" asp-for="UploadedFile" />
                        <input type="submit" asp-page-handler="Upload" value="Upload" /><br />
                        <br />
                    </td>
                </tr>
            </table>
            <div style="text-align: center;">
                <input type="submit" value="Ok" asp-page-handler="Clear" onclick="ok()" />
                <input type="submit" value="Cancel" asp-page-handler="Clear" onclick="closeDialog()" />
                <br /><br />
            </div>
        </div>
    </form>
    <script>
		document.getElementById("fileList").focus();

		function newDirectory() {
			var name = prompt('Enter name of folder:');
			if (name == null || name == '') {
				return false;
			}
			document.getElementById('NewDirectoryName').value = name;
			return true;
		}

		function renameFile() {
			var name = prompt('Enter new filename:','@(Model.FileListValue)');
			if (name == null || name == '')
				return false;
			document.getElementById('newFileName').value = name;
			return true;
		}

		function ok() {
			var dialog = window.top.opener.CKEDITOR.dialog.getCurrent();
			dialog.setValueOf('info', 'url', encodeURI('@(Model.FileUrl)'));
			closeDialog();
		}

		function closeDialog() {
			window.top.close();
			window.top.opener.focus();
		}
    </script>
</body>
</html>